"""add language to posts

Revision ID: 1fe6b3d07c2d
Revises: ea4401a7212f
Create Date: 2020-11-15 20:13:35.867076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1fe6b3d07c2d"
down_revision = "ea4401a7212f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("post", sa.Column("language", sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("post", "language")
    # ### end Alembic commands ###
