"""ew fields in user model

Revision ID: cab9d9b7581b
Revises: a4fb577b1140
Create Date: 2020-11-12 11:46:36.536404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cab9d9b7581b"
down_revision = "a4fb577b1140"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("about_me", sa.String(length=140), nullable=True))
    op.add_column("user", sa.Column("last_seen", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "last_seen")
    op.drop_column("user", "about_me")
    # ### end Alembic commands ###
